#[test]
fn canonical_source_is_role_free_and_types_only() {
    let source = signal_message::MESSAGE_INTERFACE_SOURCE;
    assert!(source.starts_with("Interface.{1 0 0}\n[]\n{"));
    assert!(source.contains("\n  []\n  []\n  []\n  ["));
    for declaration in [
        "MessageSubmission.",
        "StampedMessageSubmission.",
        "ThreadContents.",
    ] {
        assert!(source.contains(declaration), "missing {declaration}");
    }
}

#[test]
fn strict_projection_exposes_encoded_type_coordinates_only() {
    let rust = signal_message::MESSAGE_INTERFACE_RUST;
    assert!(rust.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface"
    ));
    assert!(rust.contains("pub struct z2VY2v"));
    assert!(!rust.contains("pub struct MessageSubmission"));
    assert!(!rust.contains("pub enum MessageKind"));
}
