// @generated by schema-rust from an authority-verified bootstrap Interface

pub struct z2Vb4S(Vec<z2VRQt>);
impl z2Vb4S {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VRQt>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VRQt> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VRQt> {
        self.0
    }
}
pub struct z2Vf92(std::string::String);
impl z2Vf92 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VUUz ( z2VQY5 ,) ;
pub enum z2Vdpc {z2VRYp , z2Vb3J ,} 
pub struct z2VPq6 {
    pub field_0: z2Vdkj,
    pub field_1: z2VTaw,
}
pub struct z2Vari(std::string::String);
impl z2Vari {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VRPH(Vec<z2Vc1h>);
impl z2VRPH {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2Vc1h>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2Vc1h> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2Vc1h> {
        self.0
    }
}
pub struct z2Vcjf {
    pub field_0: z2VSgb,
    pub field_1: z2VYa4,
}
pub struct z2VSVi ( z2Vari ,) ;
pub struct z2VQy1 ( z2VNPW ,) ;
pub enum z2VdsV {z2VXeo , z2Vcnf ,} 
pub enum z2VLsC {z2VNAm , z2VQEV , z2Vd2H , z2Vbd2 , z2VSMR , z2VQ4p , z2VT63 , z2VMAg , z2VPq9 ,} 
pub struct z2VRQt {
    pub field_0: z2VLZR,
    pub field_1: z2VW54,
    pub field_2: z2VNcG,
    pub field_3: z2VTiK,
    pub field_4: z2VY18,
}
pub enum z2VVDs {z2VRQJ , z2VaXN ( z2Vcjf ,) ,} 
pub struct z2VdUj(std::string::String);
impl z2VdUj {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VY18 ( z2Vf2p ,) ;
pub struct z2VPn2(u64);
impl z2VPn2 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VYf6 {
    pub field_0: z2VLsC,
    pub field_1: z2Vc6L,
}
pub struct z2VTaw(std::string::String);
impl z2VTaw {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VSgb(std::string::String);
impl z2VSgb {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VLC8 {z2VLjY ,} 
pub enum z2Vcfd {z2VNpk ( z2VTE1 ,) , z2VRLv ,} 
pub struct z2Vd8W(std::string::String);
impl z2Vd8W {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VYrY(u64);
impl z2VYrY {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2Vbmb {z2VSMd , z2VbAt ,} 
pub struct z2VYZK(u64);
impl z2VYZK {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VNbH {z2Vb3C ( z2VMBf ,) , z2VZTo ,} 
pub struct z2VTE1 {
    pub field_0: z2VPEW,
    pub field_1: z2VYrY,
}
pub enum z2VUqb {z2Vd9P ( z2VPn2 ,) , z2VZGs ( z2VLkk ,) ,} 
pub enum z2VXMQ {z2VdeM ( z2VdUj ,) , z2VNZi ,} 
pub struct z2VbGY {
    pub field_0: z2VUSt,
    pub field_1: z2Vd8W,
}
pub struct z2Vcmo(std::string::String);
impl z2Vcmo {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2Ve52 {z2VQY2 , z2Vdxv ,} 
pub struct z2VWzi(Vec<z2VQpv>);
impl z2VWzi {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VQpv>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VQpv> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VQpv> {
        self.0
    }
}
pub enum z2Vc6L {z2VX1C ( z2VaAP ,) , z2VXy5 , z2VVTa ( z2VUpa ,) ,} 
pub struct z2VNcG(std::string::String);
impl z2VNcG {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VR9d {
    pub field_0: z2VV6N,
}
pub struct z2VQDX(u64);
impl z2VQDX {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VMBf {
    pub field_0: z2VUs6,
    pub field_1: z2VRqE,
}
pub struct z2VZa8 ( z2Vcmo ,) ;
pub enum z2VaAP {z2VYw7 , z2VeQ8 , z2VPX9 , z2VXM9 ,} 
pub struct z2VevD {
    pub field_0: z2VNPW,
    pub field_1: z2Vcfd,
    pub field_2: z2VXMQ,
}
pub struct z2VUzX {
    pub field_0: z2VS1e,
}
pub struct z2Vc72 {
    pub field_0: z2VNPW,
    pub field_1: z2VNbH,
    pub field_2: z2VXMQ,
    pub field_3: z2Vbmb,
    pub field_4: z2Vcfd,
}
pub struct z2Vc1h {
    pub field_0: z2VPq6,
    pub field_1: z2VcCL,
    pub field_2: z2VYZK,
}
pub struct z2VXE7 ( z2VLZR ,) ;
pub struct z2VLtS {
    pub field_0: z2VUSt,
    pub field_1: z2VVDs,
    pub field_2: z2VMa5,
    pub field_3: z2VQDX,
}
pub struct z2VP29 ( z2VW5p ,) ;
pub struct z2Vf2p(u64);
impl z2Vf2p {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VdZd {
    pub field_0: z2VNPW,
    pub field_1: z2Vdpc,
}
pub struct z2Vasi ( z2VZuS ,) ;
pub struct z2VS1e(Vec<z2Vc72>);
impl z2VS1e {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2Vc72>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2Vc72> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2Vc72> {
        self.0
    }
}
pub struct z2VY2v {
    pub field_0: z2Vari,
    pub field_1: z2VdsV,
    pub field_2: z2VNcG,
    pub field_3: z2VTiK,
}
pub struct z2VcCL ( z2VQY5 ,) ;
pub enum z2VTJ1 {z2VWSr ( z2VY3v ,) , z2VS4W ( z2VPq6 ,) , z2VW74 ( z2Vdkj ,) ,} 
pub struct z2VLZR(u64);
impl z2VLZR {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VZuS(std::string::String);
impl z2VZuS {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VRGD {
    pub field_0: z2Vb4S,
}
pub struct z2VPEF ( z2Ve52 ,) ;
pub enum z2VPW5 {z2VZW7 , z2Veun ,} 
pub enum z2VTiK {z2VPTM ( z2VUSt ,) , z2VR2m ,} 
pub enum z2VUpa {z2Vd7N , z2VZts , z2Vem6 , z2VTL3 ,} 
pub enum z2VUs6 {z2VTin , z2VZk6 ,} 
pub struct z2VPEW(u64);
impl z2VPEW {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VNPW(std::string::String);
impl z2VNPW {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VY3v {z2VRFq , z2VVrk ( z2VLai ,) , z2Vcfq ( z2VaiJ ,) , z2VPYs ( z2VLkk ,) , z2VN6o ( z2VPn2 ,) ,} 
pub struct z2VVAD {
    pub field_0: z2VNPW,
    pub field_1: z2VMBf,
    pub field_2: z2VPEW,
    pub field_3: z2VYrY,
}
pub struct z2VMd2 {
    pub field_0: z2VUSt,
    pub field_1: z2Vd8W,
    pub field_2: z2VVDs,
}
pub struct z2VMa5(Vec<z2Vd8W>);
impl z2VMa5 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2Vd8W>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2Vd8W> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2Vd8W> {
        self.0
    }
}
pub enum z2VYJe {z2VPkz , z2VbtY ( z2VNPW ,) ,} 
pub enum z2VW5p {z2VYA6 , z2VYC4 ,} 
pub struct z2VaiJ {
    pub field_0: z2Vf92,
    pub field_1: z2VZa8,
}
pub struct z2VRqE ( z2VQY5 ,) ;
pub struct z2VZEr ( z2VPW5 ,) ;
pub struct z2VPa3 ( z2VYZK ,) ;
pub struct z2VaVk ( z2VYZK ,) ;
pub struct z2VYa4(std::string::String);
impl z2VYa4 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2Vdkj {z2VZNT , z2VUbT , z2VY7m , z2VeAv , z2VeLi , z2VYF3 , z2VPrB , z2VMBD , z2VTqZ ,} 
pub struct z2VQY5(std::string::String);
impl z2VQY5 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VQpv {
    pub field_0: z2VLZR,
    pub field_1: z2VW54,
    pub field_2: z2VNcG,
    pub field_3: z2VY18,
}
pub struct z2VLai(std::string::String);
impl z2VLai {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2Ve71 {
    pub field_0: z2VY2v,
    pub field_1: z2VTJ1,
    pub field_2: z2VY18,
}
pub struct z2VRJp ( z2VQY5 ,) ;
pub struct z2VL2C {
    pub field_0: z2VUUz,
    pub field_1: z2VPa3,
    pub field_2: z2VRJp,
    pub field_3: z2VaVk,
    pub field_4: z2VZv9,
    pub field_5: z2VRPH,
    pub field_6: z2VUqb,
}
pub struct z2VW54(std::string::String);
impl z2VW54 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VZv9 ( z2VQY5 ,) ;
pub struct z2VUSt(std::string::String);
impl z2VUSt {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VLkk(std::string::String);
impl z2VLkk {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VV6N(Vec<z2VLtS>);
impl z2VV6N {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Vec<z2VLtS>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Vec<z2VLtS> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Vec<z2VLtS> {
        self.0
    }
}
pub struct z2VVrY ( z2VUSt ,) ;
pub struct z2VYbP {
    pub field_0: z2VUSt,
    pub field_1: z2VVDs,
    pub field_2: z2VMa5,
    pub field_3: z2VWzi,
}
