// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageRecipient(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSender(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageBody(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSlot(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TimestampNanos(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WirePath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SocketMode(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnixUserIdentifier(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemPrincipal(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HostName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NetworkPeer(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentInstanceName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MessageKind {
    Send,
    Inbox,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ThreadSelection {
    None,
    Named(ThreadName),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSubmission {
    pub message_recipient: MessageRecipient,
    pub message_kind: MessageKind,
    pub message_body: MessageBody,
    pub thread_selection: ThreadSelection,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Host(HostName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OtherPersonaEngine {
    pub engine_identifier: EngineIdentifier,
    pub host: Host,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ConnectionClass {
    Owner,
    NonOwnerUser(UnixUserIdentifier),
    System(SystemPrincipal),
    OtherPersona(OtherPersonaEngine),
    Network(NetworkPeer),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentName {
    Mind,
    Message,
    Router,
    Terminal,
    Harness,
    System,
    Introspect,
    Orchestrate,
    Spirit,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InternalComponentInstanceOrigin {
    pub component_name: ComponentName,
    pub component_instance_name: ComponentInstanceName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MessageOrigin {
    Internal(ComponentName),
    InternalComponentInstance(InternalComponentInstanceOrigin),
    External(ConnectionClass),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StampedAt(TimestampNanos);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StampedMessageSubmission {
    pub message_submission: MessageSubmission,
    pub message_origin: MessageOrigin,
    pub stamped_at: StampedAt,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IngressSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentMessageIngress {
    pub internal_component_instance_origin: InternalComponentInstanceOrigin,
    pub ingress_socket_path: IngressSocketPath,
    pub socket_mode: SocketMode,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubmissionAcceptance(MessageSlot);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InboxQuery(MessageRecipient);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MessageOperationKind {
    Submit,
    SubmitStamped,
    QueryInbox,
    AssignAgentIdentity,
    BindAgentEndpoint,
    QueryAgentRegistry,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HarnessPid(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HarnessStartTime(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ResumeIdentity(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ResumeSelection {
    None,
    Resumed(ResumeIdentity),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AgentEndpointKind {
    PtySocket,
    HarnessSocket,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EndpointPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentEndpoint {
    pub agent_endpoint_kind: AgentEndpointKind,
    pub endpoint_path: EndpointPath,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EndpointSelection {
    None,
    Bound(AgentEndpoint),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AgentDeathMark {
    NotDead,
    Killed,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentIdentityAssignment {
    pub harness_pid: HarnessPid,
    pub harness_start_time: HarnessStartTime,
    pub resume_selection: ResumeSelection,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum IdentityProvenance {
    Minted,
    Reused,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AssignedAgentIdentity {
    pub agent_identifier: AgentIdentifier,
    pub identity_provenance: IdentityProvenance,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentEndpointBinding {
    pub agent_identifier: AgentIdentifier,
    pub agent_endpoint: AgentEndpoint,
    pub harness_pid: HarnessPid,
    pub harness_start_time: HarnessStartTime,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BoundAgentEndpoint(AgentIdentifier);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum AgentRegistryQuery {
    All,
    ByAgent(AgentIdentifier),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentRegistryEntry {
    pub agent_identifier: AgentIdentifier,
    pub endpoint_selection: EndpointSelection,
    pub resume_selection: ResumeSelection,
    pub agent_death_mark: AgentDeathMark,
    pub harness_pid: HarnessPid,
    pub harness_start_time: HarnessStartTime,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Entries(Vec<AgentRegistryEntry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentRegistryListing(Entries);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AgentRegistryRejectionReason {
    UnknownAgentIdentifier,
    IdentifierSpanExhausted,
    StoreRejected,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentRegistryRejection(AgentRegistryRejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InboxEntry {
    pub message_slot: MessageSlot,
    pub message_sender: MessageSender,
    pub message_body: MessageBody,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Messages(Vec<InboxEntry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InboxListing(Messages);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SubmissionRejectionReason {
    StoreRejected,
    RecipientNotFound,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubmissionRejection(SubmissionRejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DependencyKind {
    Router,
    Mind,
    Harness,
    Terminal,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ResourceKind {
    MessageSocket,
    RouterSocket,
    PeerCredentials,
    Store,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MessageUnimplementedReason {
    NotInPrototypeScope,
    DependencyMissing(DependencyKind),
    ResourceUnavailable(ResourceKind),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageRequestUnimplemented {
    pub message_operation_kind: MessageOperationKind,
    pub message_unimplemented_reason: MessageUnimplementedReason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum OwnerIdentity {
    UnixUser(UnixUserIdentifier),
    System(SystemPrincipal),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSocketMode(SocketMode);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SupervisionSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SupervisionSocketMode(SocketMode);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct ComponentIngresses(Vec<ComponentMessageIngress>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageDaemonConfiguration {
    pub message_socket_path: MessageSocketPath,
    pub message_socket_mode: MessageSocketMode,
    pub supervision_socket_path: SupervisionSocketPath,
    pub supervision_socket_mode: SupervisionSocketMode,
    pub router_socket_path: RouterSocketPath,
    pub(crate) component_ingresses: ComponentIngresses,
    pub owner_identity: OwnerIdentity,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Submit(MessageSubmission),
    SubmitStamped(StampedMessageSubmission),
    QueryInbox(InboxQuery),
    AssignAgentIdentity(AgentIdentityAssignment),
    BindAgentEndpoint(AgentEndpointBinding),
    QueryAgentRegistry(AgentRegistryQuery),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SubmissionAccepted(SubmissionAcceptance),
    SubmissionRejected(SubmissionRejection),
    InboxListing(InboxListing),
    AgentIdentityAssigned(AssignedAgentIdentity),
    AgentEndpointBound(BoundAgentEndpoint),
    AgentRegistryListing(AgentRegistryListing),
    AgentRegistryRejected(AgentRegistryRejection),
    MessageRequestUnimplemented(MessageRequestUnimplemented),
}

#[rustfmt::skip]
impl MessageRecipient {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for MessageRecipient {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MessageSender {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for MessageSender {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MessageBody {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for MessageBody {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MessageSlot {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for MessageSlot {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TimestampNanos {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TimestampNanos {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WirePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for WirePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SocketMode {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SocketMode {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnixUserIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for UnixUserIdentifier {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SystemPrincipal {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SystemPrincipal {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EngineIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EngineIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HostName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for HostName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NetworkPeer {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for NetworkPeer {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentInstanceName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ComponentInstanceName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ThreadName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ThreadName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Host {
    pub fn new(payload: HostName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &HostName {
        &self.0
    }
    pub fn into_payload(self) -> HostName {
        self.0
    }
}
#[rustfmt::skip]
impl From<HostName> for Host {
    fn from(payload: HostName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StampedAt {
    pub fn new(payload: TimestampNanos) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TimestampNanos {
        &self.0
    }
    pub fn into_payload(self) -> TimestampNanos {
        self.0
    }
}
#[rustfmt::skip]
impl From<TimestampNanos> for StampedAt {
    fn from(payload: TimestampNanos) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IngressSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for IngressSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubmissionAcceptance {
    pub fn new(payload: MessageSlot) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageSlot {
        &self.0
    }
    pub fn into_payload(self) -> MessageSlot {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageSlot> for SubmissionAcceptance {
    fn from(payload: MessageSlot) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InboxQuery {
    pub fn new(payload: MessageRecipient) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageRecipient {
        &self.0
    }
    pub fn into_payload(self) -> MessageRecipient {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageRecipient> for InboxQuery {
    fn from(payload: MessageRecipient) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for AgentIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HarnessPid {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for HarnessPid {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HarnessStartTime {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for HarnessStartTime {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ResumeIdentity {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ResumeIdentity {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EndpointPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for EndpointPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl BoundAgentEndpoint {
    pub fn new(payload: AgentIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AgentIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> AgentIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<AgentIdentifier> for BoundAgentEndpoint {
    fn from(payload: AgentIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Entries {
    pub fn new(payload: Vec<AgentRegistryEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<AgentRegistryEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<AgentRegistryEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<AgentRegistryEntry>> for Entries {
    fn from(payload: Vec<AgentRegistryEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentRegistryListing {
    pub fn new(payload: Entries) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Entries {
        &self.0
    }
    pub fn into_payload(self) -> Entries {
        self.0
    }
}
#[rustfmt::skip]
impl From<Entries> for AgentRegistryListing {
    fn from(payload: Entries) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentRegistryRejection {
    pub fn new(payload: AgentRegistryRejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AgentRegistryRejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> AgentRegistryRejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<AgentRegistryRejectionReason> for AgentRegistryRejection {
    fn from(payload: AgentRegistryRejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Messages {
    pub fn new(payload: Vec<InboxEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<InboxEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<InboxEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<InboxEntry>> for Messages {
    fn from(payload: Vec<InboxEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InboxListing {
    pub fn new(payload: Messages) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Messages {
        &self.0
    }
    pub fn into_payload(self) -> Messages {
        self.0
    }
}
#[rustfmt::skip]
impl From<Messages> for InboxListing {
    fn from(payload: Messages) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubmissionRejection {
    pub fn new(payload: SubmissionRejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubmissionRejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> SubmissionRejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubmissionRejectionReason> for SubmissionRejection {
    fn from(payload: SubmissionRejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MessageSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for MessageSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MessageSocketMode {
    pub fn new(payload: SocketMode) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SocketMode {
        &self.0
    }
    pub fn into_payload(self) -> SocketMode {
        self.0
    }
}
#[rustfmt::skip]
impl From<SocketMode> for MessageSocketMode {
    fn from(payload: SocketMode) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SupervisionSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for SupervisionSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SupervisionSocketMode {
    pub fn new(payload: SocketMode) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SocketMode {
        &self.0
    }
    pub fn into_payload(self) -> SocketMode {
        self.0
    }
}
#[rustfmt::skip]
impl From<SocketMode> for SupervisionSocketMode {
    fn from(payload: SocketMode) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RouterSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for RouterSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentIngresses {
    pub fn new(payload: Vec<ComponentMessageIngress>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ComponentMessageIngress> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ComponentMessageIngress> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ComponentMessageIngress>> for ComponentIngresses {
    fn from(payload: Vec<ComponentMessageIngress>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ThreadSelection {
    pub fn named(payload: String) -> Self {
        Self::Named(ThreadName::new(payload))
    }
}

#[rustfmt::skip]
impl ConnectionClass {
    pub fn non_owner_user(payload: Integer) -> Self {
        Self::NonOwnerUser(UnixUserIdentifier::new(payload))
    }
    pub fn system(payload: String) -> Self {
        Self::System(SystemPrincipal::new(payload))
    }
    pub fn other_persona(payload: OtherPersonaEngine) -> Self {
        Self::OtherPersona(payload)
    }
    pub fn network(payload: String) -> Self {
        Self::Network(NetworkPeer::new(payload))
    }
}

#[rustfmt::skip]
impl MessageOrigin {
    pub fn internal(payload: ComponentName) -> Self {
        Self::Internal(payload)
    }
    pub fn internal_component_instance(
        payload: InternalComponentInstanceOrigin,
    ) -> Self {
        Self::InternalComponentInstance(payload)
    }
    pub fn external(payload: ConnectionClass) -> Self {
        Self::External(payload)
    }
}

#[rustfmt::skip]
impl ResumeSelection {
    pub fn resumed(payload: String) -> Self {
        Self::Resumed(ResumeIdentity::new(payload))
    }
}

#[rustfmt::skip]
impl EndpointSelection {
    pub fn bound(payload: AgentEndpoint) -> Self {
        Self::Bound(payload)
    }
}

#[rustfmt::skip]
impl AgentRegistryQuery {
    pub fn by_agent(payload: String) -> Self {
        Self::ByAgent(AgentIdentifier::new(payload))
    }
}

#[rustfmt::skip]
impl MessageUnimplementedReason {
    pub fn dependency_missing(payload: DependencyKind) -> Self {
        Self::DependencyMissing(payload)
    }
    pub fn resource_unavailable(payload: ResourceKind) -> Self {
        Self::ResourceUnavailable(payload)
    }
}

#[rustfmt::skip]
impl OwnerIdentity {
    pub fn unix_user(payload: Integer) -> Self {
        Self::UnixUser(UnixUserIdentifier::new(payload))
    }
    pub fn system(payload: String) -> Self {
        Self::System(SystemPrincipal::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn submit(payload: MessageSubmission) -> Self {
        Self::Submit(payload)
    }
    pub fn submit_stamped(payload: StampedMessageSubmission) -> Self {
        Self::SubmitStamped(payload)
    }
    pub fn query_inbox(payload: MessageRecipient) -> Self {
        Self::QueryInbox(InboxQuery::new(payload))
    }
    pub fn assign_agent_identity(payload: AgentIdentityAssignment) -> Self {
        Self::AssignAgentIdentity(payload)
    }
    pub fn bind_agent_endpoint(payload: AgentEndpointBinding) -> Self {
        Self::BindAgentEndpoint(payload)
    }
    pub fn query_agent_registry(payload: AgentRegistryQuery) -> Self {
        Self::QueryAgentRegistry(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn submission_accepted(payload: MessageSlot) -> Self {
        Self::SubmissionAccepted(SubmissionAcceptance::new(payload))
    }
    pub fn submission_rejected(payload: SubmissionRejectionReason) -> Self {
        Self::SubmissionRejected(SubmissionRejection::new(payload))
    }
    pub fn inbox_listing(payload: Messages) -> Self {
        Self::InboxListing(InboxListing::new(payload))
    }
    pub fn agent_identity_assigned(payload: AssignedAgentIdentity) -> Self {
        Self::AgentIdentityAssigned(payload)
    }
    pub fn agent_endpoint_bound(payload: AgentIdentifier) -> Self {
        Self::AgentEndpointBound(BoundAgentEndpoint::new(payload))
    }
    pub fn agent_registry_listing(payload: Entries) -> Self {
        Self::AgentRegistryListing(AgentRegistryListing::new(payload))
    }
    pub fn agent_registry_rejected(payload: AgentRegistryRejectionReason) -> Self {
        Self::AgentRegistryRejected(AgentRegistryRejection::new(payload))
    }
    pub fn message_request_unimplemented(payload: MessageRequestUnimplemented) -> Self {
        Self::MessageRequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<ThreadName> for ThreadSelection {
    fn from(payload: ThreadName) -> Self {
        Self::Named(payload)
    }
}

#[rustfmt::skip]
impl From<UnixUserIdentifier> for ConnectionClass {
    fn from(payload: UnixUserIdentifier) -> Self {
        Self::NonOwnerUser(payload)
    }
}

#[rustfmt::skip]
impl From<SystemPrincipal> for ConnectionClass {
    fn from(payload: SystemPrincipal) -> Self {
        Self::System(payload)
    }
}

#[rustfmt::skip]
impl From<OtherPersonaEngine> for ConnectionClass {
    fn from(payload: OtherPersonaEngine) -> Self {
        Self::OtherPersona(payload)
    }
}

#[rustfmt::skip]
impl From<NetworkPeer> for ConnectionClass {
    fn from(payload: NetworkPeer) -> Self {
        Self::Network(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentName> for MessageOrigin {
    fn from(payload: ComponentName) -> Self {
        Self::Internal(payload)
    }
}

#[rustfmt::skip]
impl From<InternalComponentInstanceOrigin> for MessageOrigin {
    fn from(payload: InternalComponentInstanceOrigin) -> Self {
        Self::InternalComponentInstance(payload)
    }
}

#[rustfmt::skip]
impl From<ConnectionClass> for MessageOrigin {
    fn from(payload: ConnectionClass) -> Self {
        Self::External(payload)
    }
}

#[rustfmt::skip]
impl From<ResumeIdentity> for ResumeSelection {
    fn from(payload: ResumeIdentity) -> Self {
        Self::Resumed(payload)
    }
}

#[rustfmt::skip]
impl From<AgentEndpoint> for EndpointSelection {
    fn from(payload: AgentEndpoint) -> Self {
        Self::Bound(payload)
    }
}

#[rustfmt::skip]
impl From<AgentIdentifier> for AgentRegistryQuery {
    fn from(payload: AgentIdentifier) -> Self {
        Self::ByAgent(payload)
    }
}

#[rustfmt::skip]
impl From<DependencyKind> for MessageUnimplementedReason {
    fn from(payload: DependencyKind) -> Self {
        Self::DependencyMissing(payload)
    }
}

#[rustfmt::skip]
impl From<ResourceKind> for MessageUnimplementedReason {
    fn from(payload: ResourceKind) -> Self {
        Self::ResourceUnavailable(payload)
    }
}

#[rustfmt::skip]
impl From<UnixUserIdentifier> for OwnerIdentity {
    fn from(payload: UnixUserIdentifier) -> Self {
        Self::UnixUser(payload)
    }
}

#[rustfmt::skip]
impl From<SystemPrincipal> for OwnerIdentity {
    fn from(payload: SystemPrincipal) -> Self {
        Self::System(payload)
    }
}

#[rustfmt::skip]
impl From<MessageSubmission> for Input {
    fn from(payload: MessageSubmission) -> Self {
        Self::Submit(payload)
    }
}

#[rustfmt::skip]
impl From<StampedMessageSubmission> for Input {
    fn from(payload: StampedMessageSubmission) -> Self {
        Self::SubmitStamped(payload)
    }
}

#[rustfmt::skip]
impl From<InboxQuery> for Input {
    fn from(payload: InboxQuery) -> Self {
        Self::QueryInbox(payload)
    }
}

#[rustfmt::skip]
impl From<AgentIdentityAssignment> for Input {
    fn from(payload: AgentIdentityAssignment) -> Self {
        Self::AssignAgentIdentity(payload)
    }
}

#[rustfmt::skip]
impl From<AgentEndpointBinding> for Input {
    fn from(payload: AgentEndpointBinding) -> Self {
        Self::BindAgentEndpoint(payload)
    }
}

#[rustfmt::skip]
impl From<AgentRegistryQuery> for Input {
    fn from(payload: AgentRegistryQuery) -> Self {
        Self::QueryAgentRegistry(payload)
    }
}

#[rustfmt::skip]
impl From<SubmissionAcceptance> for Output {
    fn from(payload: SubmissionAcceptance) -> Self {
        Self::SubmissionAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<SubmissionRejection> for Output {
    fn from(payload: SubmissionRejection) -> Self {
        Self::SubmissionRejected(payload)
    }
}

#[rustfmt::skip]
impl From<InboxListing> for Output {
    fn from(payload: InboxListing) -> Self {
        Self::InboxListing(payload)
    }
}

#[rustfmt::skip]
impl From<AssignedAgentIdentity> for Output {
    fn from(payload: AssignedAgentIdentity) -> Self {
        Self::AgentIdentityAssigned(payload)
    }
}

#[rustfmt::skip]
impl From<BoundAgentEndpoint> for Output {
    fn from(payload: BoundAgentEndpoint) -> Self {
        Self::AgentEndpointBound(payload)
    }
}

#[rustfmt::skip]
impl From<AgentRegistryListing> for Output {
    fn from(payload: AgentRegistryListing) -> Self {
        Self::AgentRegistryListing(payload)
    }
}

#[rustfmt::skip]
impl From<AgentRegistryRejection> for Output {
    fn from(payload: AgentRegistryRejection) -> Self {
        Self::AgentRegistryRejected(payload)
    }
}

#[rustfmt::skip]
impl From<MessageRequestUnimplemented> for Output {
    fn from(payload: MessageRequestUnimplemented) -> Self {
        Self::MessageRequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_SUBMIT: u64 = 0x0000000000000000;
    pub const INPUT_SUBMIT_STAMPED: u64 = 0x0001000000000000;
    pub const INPUT_QUERY_INBOX: u64 = 0x0002000000000000;
    pub const INPUT_ASSIGN_AGENT_IDENTITY: u64 = 0x0003000000000000;
    pub const INPUT_BIND_AGENT_ENDPOINT: u64 = 0x0004000000000000;
    pub const INPUT_QUERY_AGENT_REGISTRY: u64 = 0x0005000000000000;
    pub const OUTPUT_SUBMISSION_ACCEPTED: u64 = 0x0100000000000000;
    pub const OUTPUT_SUBMISSION_REJECTED: u64 = 0x0101000000000000;
    pub const OUTPUT_INBOX_LISTING: u64 = 0x0102000000000000;
    pub const OUTPUT_AGENT_IDENTITY_ASSIGNED: u64 = 0x0103000000000000;
    pub const OUTPUT_AGENT_ENDPOINT_BOUND: u64 = 0x0104000000000000;
    pub const OUTPUT_AGENT_REGISTRY_LISTING: u64 = 0x0105000000000000;
    pub const OUTPUT_AGENT_REGISTRY_REJECTED: u64 = 0x0106000000000000;
    pub const OUTPUT_MESSAGE_REQUEST_UNIMPLEMENTED: u64 = 0x0107000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Submit,
    SubmitStamped,
    QueryInbox,
    AssignAgentIdentity,
    BindAgentEndpoint,
    QueryAgentRegistry,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "nota-text",
    derive(nota::NotaDecode, nota::NotaDecodeTraced, nota::NotaEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    SubmissionAccepted,
    SubmissionRejected,
    InboxListing,
    AgentIdentityAssigned,
    AgentEndpointBound,
    AgentRegistryListing,
    AgentRegistryRejected,
    MessageRequestUnimplemented,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Submit(_) => InputRoute::Submit,
            Self::SubmitStamped(_) => InputRoute::SubmitStamped,
            Self::QueryInbox(_) => InputRoute::QueryInbox,
            Self::AssignAgentIdentity(_) => InputRoute::AssignAgentIdentity,
            Self::BindAgentEndpoint(_) => InputRoute::BindAgentEndpoint,
            Self::QueryAgentRegistry(_) => InputRoute::QueryAgentRegistry,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Submit(_) => short_header::INPUT_SUBMIT,
            Self::SubmitStamped(_) => short_header::INPUT_SUBMIT_STAMPED,
            Self::QueryInbox(_) => short_header::INPUT_QUERY_INBOX,
            Self::AssignAgentIdentity(_) => short_header::INPUT_ASSIGN_AGENT_IDENTITY,
            Self::BindAgentEndpoint(_) => short_header::INPUT_BIND_AGENT_ENDPOINT,
            Self::QueryAgentRegistry(_) => short_header::INPUT_QUERY_AGENT_REGISTRY,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_SUBMIT => Ok(InputRoute::Submit),
            short_header::INPUT_SUBMIT_STAMPED => Ok(InputRoute::SubmitStamped),
            short_header::INPUT_QUERY_INBOX => Ok(InputRoute::QueryInbox),
            short_header::INPUT_ASSIGN_AGENT_IDENTITY => {
                Ok(InputRoute::AssignAgentIdentity)
            }
            short_header::INPUT_BIND_AGENT_ENDPOINT => Ok(InputRoute::BindAgentEndpoint),
            short_header::INPUT_QUERY_AGENT_REGISTRY => {
                Ok(InputRoute::QueryAgentRegistry)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::SubmissionAccepted(_) => OutputRoute::SubmissionAccepted,
            Self::SubmissionRejected(_) => OutputRoute::SubmissionRejected,
            Self::InboxListing(_) => OutputRoute::InboxListing,
            Self::AgentIdentityAssigned(_) => OutputRoute::AgentIdentityAssigned,
            Self::AgentEndpointBound(_) => OutputRoute::AgentEndpointBound,
            Self::AgentRegistryListing(_) => OutputRoute::AgentRegistryListing,
            Self::AgentRegistryRejected(_) => OutputRoute::AgentRegistryRejected,
            Self::MessageRequestUnimplemented(_) => {
                OutputRoute::MessageRequestUnimplemented
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::SubmissionAccepted(_) => short_header::OUTPUT_SUBMISSION_ACCEPTED,
            Self::SubmissionRejected(_) => short_header::OUTPUT_SUBMISSION_REJECTED,
            Self::InboxListing(_) => short_header::OUTPUT_INBOX_LISTING,
            Self::AgentIdentityAssigned(_) => {
                short_header::OUTPUT_AGENT_IDENTITY_ASSIGNED
            }
            Self::AgentEndpointBound(_) => short_header::OUTPUT_AGENT_ENDPOINT_BOUND,
            Self::AgentRegistryListing(_) => short_header::OUTPUT_AGENT_REGISTRY_LISTING,
            Self::AgentRegistryRejected(_) => {
                short_header::OUTPUT_AGENT_REGISTRY_REJECTED
            }
            Self::MessageRequestUnimplemented(_) => {
                short_header::OUTPUT_MESSAGE_REQUEST_UNIMPLEMENTED
            }
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_SUBMISSION_ACCEPTED => {
                Ok(OutputRoute::SubmissionAccepted)
            }
            short_header::OUTPUT_SUBMISSION_REJECTED => {
                Ok(OutputRoute::SubmissionRejected)
            }
            short_header::OUTPUT_INBOX_LISTING => Ok(OutputRoute::InboxListing),
            short_header::OUTPUT_AGENT_IDENTITY_ASSIGNED => {
                Ok(OutputRoute::AgentIdentityAssigned)
            }
            short_header::OUTPUT_AGENT_ENDPOINT_BOUND => {
                Ok(OutputRoute::AgentEndpointBound)
            }
            short_header::OUTPUT_AGENT_REGISTRY_LISTING => {
                Ok(OutputRoute::AgentRegistryListing)
            }
            short_header::OUTPUT_AGENT_REGISTRY_REJECTED => {
                Ok(OutputRoute::AgentRegistryRejected)
            }
            short_header::OUTPUT_MESSAGE_REQUEST_UNIMPLEMENTED => {
                Ok(OutputRoute::MessageRequestUnimplemented)
            }
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Submit",
        "SubmitStamped",
        "QueryInbox",
        "AssignAgentIdentity",
        "BindAgentEndpoint",
        "QueryAgentRegistry",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
