// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
pub use dotos::{DotosDecodeError, DotosEncode, DotosSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageRecipient(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSender(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageBody(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSlot(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TimestampNanos(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct WirePath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SocketMode(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnixUserIdentifier(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemPrincipal(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HostName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NetworkPeer(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentInstanceName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MessageKind {
    Send,
    Inbox,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ThreadSelection {
    None,
    Named(ThreadName),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSubmission {
    pub message_recipient: MessageRecipient,
    pub message_kind: MessageKind,
    pub message_body: MessageBody,
    pub thread_selection: ThreadSelection,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Host(HostName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OtherPersonaEngine {
    pub engine_identifier: EngineIdentifier,
    pub host: Host,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ConnectionClass {
    Owner,
    NonOwnerUser(UnixUserIdentifier),
    System(SystemPrincipal),
    OtherPersona(OtherPersonaEngine),
    Network(NetworkPeer),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentName {
    Mind,
    Message,
    Router,
    Terminal,
    Harness,
    System,
    Introspect,
    Orchestrate,
    Spirit,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InternalComponentInstanceOrigin {
    pub component_name: ComponentName,
    pub component_instance_name: ComponentInstanceName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MessageOrigin {
    Internal(ComponentName),
    InternalComponentInstance(InternalComponentInstanceOrigin),
    External(ConnectionClass),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StampedAt(TimestampNanos);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StampedMessageSubmission {
    pub message_submission: MessageSubmission,
    pub message_origin: MessageOrigin,
    pub stamped_at: StampedAt,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IngressSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentMessageIngress {
    pub internal_component_instance_origin: InternalComponentInstanceOrigin,
    pub ingress_socket_path: IngressSocketPath,
    pub socket_mode: SocketMode,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubmissionAcceptance(MessageSlot);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InboxQuery(MessageRecipient);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum MessageOperationKind {
    Submit,
    SubmitStamped,
    QueryInbox,
    AssignAgentIdentity,
    BindAgentEndpoint,
    QueryAgentRegistry,
    QueryThread,
    SubscribeThread,
    QueryThreads,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HarnessPid(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HarnessStartTime(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ResumeIdentity(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ResumeSelection {
    None,
    Resumed(ResumeIdentity),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AgentEndpointKind {
    PtySocket,
    HarnessSocket,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EndpointPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentEndpoint {
    pub agent_endpoint_kind: AgentEndpointKind,
    pub endpoint_path: EndpointPath,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum EndpointSelection {
    None,
    Bound(AgentEndpoint),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AgentDeathMark {
    NotDead,
    Killed,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HarnessProcessPin {
    pub harness_pid: HarnessPid,
    pub harness_start_time: HarnessStartTime,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ProcessPinSelection {
    None,
    Pinned(HarnessProcessPin),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentIdentityAssignment {
    pub agent_identifier: AgentIdentifier,
    pub process_pin_selection: ProcessPinSelection,
    pub resume_selection: ResumeSelection,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum IdentityProvenance {
    Seated,
    Reseated,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AssignedAgentIdentity {
    pub agent_identifier: AgentIdentifier,
    pub identity_provenance: IdentityProvenance,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentEndpointBinding {
    pub agent_identifier: AgentIdentifier,
    pub agent_endpoint: AgentEndpoint,
    pub harness_pid: HarnessPid,
    pub harness_start_time: HarnessStartTime,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct BoundAgentEndpoint(AgentIdentifier);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum AgentRegistryQuery {
    All,
    ByAgent(AgentIdentifier),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentRegistryEntry {
    pub agent_identifier: AgentIdentifier,
    pub endpoint_selection: EndpointSelection,
    pub resume_selection: ResumeSelection,
    pub agent_death_mark: AgentDeathMark,
    pub process_pin_selection: ProcessPinSelection,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Entries(Vec<AgentRegistryEntry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentRegistryListingReply(Entries);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum AgentRegistryRejectionReason {
    UnknownAgentIdentifier,
    StoreRejected,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct AgentRegistryRejection(AgentRegistryRejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InboxEntry {
    pub message_slot: MessageSlot,
    pub message_sender: MessageSender,
    pub message_body: MessageBody,
    pub thread_selection: ThreadSelection,
    pub stamped_at: StampedAt,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Messages(Vec<InboxEntry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InboxListingReply(Messages);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum SubmissionRejectionReason {
    StoreRejected,
    RecipientNotFound,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SubmissionRejection(SubmissionRejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ErrorMessage(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ErrorReport(ErrorMessage);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadQuery(ThreadName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RepositoryName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct FeatureBranchName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadRelation {
    pub repository_name: RepositoryName,
    pub feature_branch_name: FeatureBranchName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ThreadRelationSelection {
    None,
    Related(ThreadRelation),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ParticipantName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadSubscription {
    pub thread_name: ThreadName,
    pub participant_name: ParticipantName,
    pub thread_relation_selection: ThreadRelationSelection,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadSubscriptionAcknowledgment {
    pub thread_name: ThreadName,
    pub participant_name: ParticipantName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadEntry {
    pub message_slot: MessageSlot,
    pub message_sender: MessageSender,
    pub message_body: MessageBody,
    pub stamped_at: StampedAt,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Participants(Vec<ParticipantName>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadEntries(Vec<ThreadEntry>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadContents {
    pub thread_name: ThreadName,
    pub thread_relation_selection: ThreadRelationSelection,
    pub participants: Participants,
    pub thread_entries: ThreadEntries,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ThreadIndexQuery {
    All,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageCount(Integer);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadSummary {
    pub thread_name: ThreadName,
    pub thread_relation_selection: ThreadRelationSelection,
    pub participants: Participants,
    pub message_count: MessageCount,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct Threads(Vec<ThreadSummary>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadIndexEntries(Threads);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ThreadRejectionReason {
    UnknownThread,
    StoreRejected,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ThreadRejection(ThreadRejectionReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DependencyKind {
    Router,
    Mind,
    Harness,
    Terminal,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ResourceKind {
    MessageSocket,
    RouterSocket,
    PeerCredentials,
    Store,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MessageUnimplementedReason {
    NotInPrototypeScope,
    DependencyMissing(DependencyKind),
    ResourceUnavailable(ResourceKind),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageRequestUnimplementedReply {
    pub message_operation_kind: MessageOperationKind,
    pub message_unimplemented_reason: MessageUnimplementedReason,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum OwnerIdentity {
    UnixUser(UnixUserIdentifier),
    System(SystemPrincipal),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageSocketMode(SocketMode);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SupervisionSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SupervisionSocketMode(SocketMode);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RouterSocketPath(WirePath);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct ComponentIngresses(Vec<ComponentMessageIngress>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct MessageDaemonConfiguration {
    pub message_socket_path: MessageSocketPath,
    pub message_socket_mode: MessageSocketMode,
    pub supervision_socket_path: SupervisionSocketPath,
    pub supervision_socket_mode: SupervisionSocketMode,
    pub router_socket_path: RouterSocketPath,
    pub(crate) component_ingresses: ComponentIngresses,
    pub owner_identity: OwnerIdentity,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Submit(MessageSubmission),
    SubmitStamped(StampedMessageSubmission),
    QueryInbox(InboxQuery),
    AssignAgentIdentity(AgentIdentityAssignment),
    BindAgentEndpoint(AgentEndpointBinding),
    QueryAgentRegistry(AgentRegistryQuery),
    QueryThread(ThreadQuery),
    SubscribeThread(ThreadSubscription),
    QueryThreads(ThreadIndexQuery),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    SubmissionAccepted(SubmissionAcceptance),
    SubmissionRejected(SubmissionRejection),
    InboxListing(InboxListingReply),
    AgentIdentityAssigned(AssignedAgentIdentity),
    AgentEndpointBound(BoundAgentEndpoint),
    AgentRegistryListing(AgentRegistryListingReply),
    AgentRegistryRejected(AgentRegistryRejection),
    MessageRequestUnimplemented(MessageRequestUnimplementedReply),
    Error(ErrorReport),
    ThreadListing(ThreadContents),
    ThreadSubscribed(ThreadSubscriptionAcknowledgment),
    ThreadIndexListing(ThreadIndexEntries),
    ThreadRejected(ThreadRejection),
}

#[rustfmt::skip]
impl MessageRecipient {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for MessageRecipient {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MessageSender {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for MessageSender {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MessageBody {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for MessageBody {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MessageSlot {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for MessageSlot {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TimestampNanos {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for TimestampNanos {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl WirePath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for WirePath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SocketMode {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for SocketMode {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnixUserIdentifier {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for UnixUserIdentifier {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SystemPrincipal {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SystemPrincipal {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EngineIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EngineIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HostName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for HostName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NetworkPeer {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for NetworkPeer {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentInstanceName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ComponentInstanceName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ThreadName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ThreadName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Host {
    pub fn new(payload: HostName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &HostName {
        &self.0
    }
    pub fn into_payload(self) -> HostName {
        self.0
    }
}
#[rustfmt::skip]
impl From<HostName> for Host {
    fn from(payload: HostName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StampedAt {
    pub fn new(payload: TimestampNanos) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &TimestampNanos {
        &self.0
    }
    pub fn into_payload(self) -> TimestampNanos {
        self.0
    }
}
#[rustfmt::skip]
impl From<TimestampNanos> for StampedAt {
    fn from(payload: TimestampNanos) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IngressSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for IngressSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubmissionAcceptance {
    pub fn new(payload: MessageSlot) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageSlot {
        &self.0
    }
    pub fn into_payload(self) -> MessageSlot {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageSlot> for SubmissionAcceptance {
    fn from(payload: MessageSlot) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InboxQuery {
    pub fn new(payload: MessageRecipient) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageRecipient {
        &self.0
    }
    pub fn into_payload(self) -> MessageRecipient {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageRecipient> for InboxQuery {
    fn from(payload: MessageRecipient) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for AgentIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HarnessPid {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for HarnessPid {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HarnessStartTime {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for HarnessStartTime {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ResumeIdentity {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ResumeIdentity {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EndpointPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for EndpointPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl BoundAgentEndpoint {
    pub fn new(payload: AgentIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AgentIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> AgentIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<AgentIdentifier> for BoundAgentEndpoint {
    fn from(payload: AgentIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Entries {
    pub fn new(payload: Vec<AgentRegistryEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<AgentRegistryEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<AgentRegistryEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<AgentRegistryEntry>> for Entries {
    fn from(payload: Vec<AgentRegistryEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentRegistryListingReply {
    pub fn new(payload: Entries) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Entries {
        &self.0
    }
    pub fn into_payload(self) -> Entries {
        self.0
    }
}
#[rustfmt::skip]
impl From<Entries> for AgentRegistryListingReply {
    fn from(payload: Entries) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl AgentRegistryRejection {
    pub fn new(payload: AgentRegistryRejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &AgentRegistryRejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> AgentRegistryRejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<AgentRegistryRejectionReason> for AgentRegistryRejection {
    fn from(payload: AgentRegistryRejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Messages {
    pub fn new(payload: Vec<InboxEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<InboxEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<InboxEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<InboxEntry>> for Messages {
    fn from(payload: Vec<InboxEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl InboxListingReply {
    pub fn new(payload: Messages) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Messages {
        &self.0
    }
    pub fn into_payload(self) -> Messages {
        self.0
    }
}
#[rustfmt::skip]
impl From<Messages> for InboxListingReply {
    fn from(payload: Messages) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SubmissionRejection {
    pub fn new(payload: SubmissionRejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SubmissionRejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> SubmissionRejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<SubmissionRejectionReason> for SubmissionRejection {
    fn from(payload: SubmissionRejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ErrorMessage {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ErrorMessage {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ErrorReport {
    pub fn new(payload: ErrorMessage) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ErrorMessage {
        &self.0
    }
    pub fn into_payload(self) -> ErrorMessage {
        self.0
    }
}
#[rustfmt::skip]
impl From<ErrorMessage> for ErrorReport {
    fn from(payload: ErrorMessage) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ThreadQuery {
    pub fn new(payload: ThreadName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ThreadName {
        &self.0
    }
    pub fn into_payload(self) -> ThreadName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ThreadName> for ThreadQuery {
    fn from(payload: ThreadName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RepositoryName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for RepositoryName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl FeatureBranchName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for FeatureBranchName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ParticipantName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ParticipantName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Participants {
    pub fn new(payload: Vec<ParticipantName>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ParticipantName> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ParticipantName> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ParticipantName>> for Participants {
    fn from(payload: Vec<ParticipantName>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ThreadEntries {
    pub fn new(payload: Vec<ThreadEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ThreadEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ThreadEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ThreadEntry>> for ThreadEntries {
    fn from(payload: Vec<ThreadEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MessageCount {
    pub fn new(payload: Integer) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Integer {
        &self.0
    }
    pub fn into_payload(self) -> Integer {
        self.0
    }
}
#[rustfmt::skip]
impl From<Integer> for MessageCount {
    fn from(payload: Integer) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Threads {
    pub fn new(payload: Vec<ThreadSummary>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ThreadSummary> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ThreadSummary> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ThreadSummary>> for Threads {
    fn from(payload: Vec<ThreadSummary>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ThreadIndexEntries {
    pub fn new(payload: Threads) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Threads {
        &self.0
    }
    pub fn into_payload(self) -> Threads {
        self.0
    }
}
#[rustfmt::skip]
impl From<Threads> for ThreadIndexEntries {
    fn from(payload: Threads) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ThreadRejection {
    pub fn new(payload: ThreadRejectionReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ThreadRejectionReason {
        &self.0
    }
    pub fn into_payload(self) -> ThreadRejectionReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<ThreadRejectionReason> for ThreadRejection {
    fn from(payload: ThreadRejectionReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MessageSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for MessageSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MessageSocketMode {
    pub fn new(payload: SocketMode) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SocketMode {
        &self.0
    }
    pub fn into_payload(self) -> SocketMode {
        self.0
    }
}
#[rustfmt::skip]
impl From<SocketMode> for MessageSocketMode {
    fn from(payload: SocketMode) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SupervisionSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for SupervisionSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SupervisionSocketMode {
    pub fn new(payload: SocketMode) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &SocketMode {
        &self.0
    }
    pub fn into_payload(self) -> SocketMode {
        self.0
    }
}
#[rustfmt::skip]
impl From<SocketMode> for SupervisionSocketMode {
    fn from(payload: SocketMode) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RouterSocketPath {
    pub fn new(payload: WirePath) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &WirePath {
        &self.0
    }
    pub fn into_payload(self) -> WirePath {
        self.0
    }
}
#[rustfmt::skip]
impl From<WirePath> for RouterSocketPath {
    fn from(payload: WirePath) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentIngresses {
    pub fn new(payload: Vec<ComponentMessageIngress>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<ComponentMessageIngress> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<ComponentMessageIngress> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<ComponentMessageIngress>> for ComponentIngresses {
    fn from(payload: Vec<ComponentMessageIngress>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ThreadSelection {
    pub fn named(payload: String) -> Self {
        Self::Named(ThreadName::new(payload))
    }
}

#[rustfmt::skip]
impl ConnectionClass {
    pub fn non_owner_user(payload: Integer) -> Self {
        Self::NonOwnerUser(UnixUserIdentifier::new(payload))
    }
    pub fn system(payload: String) -> Self {
        Self::System(SystemPrincipal::new(payload))
    }
    pub fn other_persona(payload: OtherPersonaEngine) -> Self {
        Self::OtherPersona(payload)
    }
    pub fn network(payload: String) -> Self {
        Self::Network(NetworkPeer::new(payload))
    }
}

#[rustfmt::skip]
impl MessageOrigin {
    pub fn internal(payload: ComponentName) -> Self {
        Self::Internal(payload)
    }
    pub fn internal_component_instance(
        payload: InternalComponentInstanceOrigin,
    ) -> Self {
        Self::InternalComponentInstance(payload)
    }
    pub fn external(payload: ConnectionClass) -> Self {
        Self::External(payload)
    }
}

#[rustfmt::skip]
impl ResumeSelection {
    pub fn resumed(payload: String) -> Self {
        Self::Resumed(ResumeIdentity::new(payload))
    }
}

#[rustfmt::skip]
impl EndpointSelection {
    pub fn bound(payload: AgentEndpoint) -> Self {
        Self::Bound(payload)
    }
}

#[rustfmt::skip]
impl ProcessPinSelection {
    pub fn pinned(payload: HarnessProcessPin) -> Self {
        Self::Pinned(payload)
    }
}

#[rustfmt::skip]
impl AgentRegistryQuery {
    pub fn by_agent(payload: String) -> Self {
        Self::ByAgent(AgentIdentifier::new(payload))
    }
}

#[rustfmt::skip]
impl ThreadRelationSelection {
    pub fn related(payload: ThreadRelation) -> Self {
        Self::Related(payload)
    }
}

#[rustfmt::skip]
impl MessageUnimplementedReason {
    pub fn dependency_missing(payload: DependencyKind) -> Self {
        Self::DependencyMissing(payload)
    }
    pub fn resource_unavailable(payload: ResourceKind) -> Self {
        Self::ResourceUnavailable(payload)
    }
}

#[rustfmt::skip]
impl OwnerIdentity {
    pub fn unix_user(payload: Integer) -> Self {
        Self::UnixUser(UnixUserIdentifier::new(payload))
    }
    pub fn system(payload: String) -> Self {
        Self::System(SystemPrincipal::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn submit(payload: MessageSubmission) -> Self {
        Self::Submit(payload)
    }
    pub fn submit_stamped(payload: StampedMessageSubmission) -> Self {
        Self::SubmitStamped(payload)
    }
    pub fn query_inbox(payload: MessageRecipient) -> Self {
        Self::QueryInbox(InboxQuery::new(payload))
    }
    pub fn assign_agent_identity(payload: AgentIdentityAssignment) -> Self {
        Self::AssignAgentIdentity(payload)
    }
    pub fn bind_agent_endpoint(payload: AgentEndpointBinding) -> Self {
        Self::BindAgentEndpoint(payload)
    }
    pub fn query_agent_registry(payload: AgentRegistryQuery) -> Self {
        Self::QueryAgentRegistry(payload)
    }
    pub fn query_thread(payload: ThreadName) -> Self {
        Self::QueryThread(ThreadQuery::new(payload))
    }
    pub fn subscribe_thread(payload: ThreadSubscription) -> Self {
        Self::SubscribeThread(payload)
    }
    pub fn query_threads(payload: ThreadIndexQuery) -> Self {
        Self::QueryThreads(payload)
    }
}

#[rustfmt::skip]
impl Output {
    pub fn submission_accepted(payload: MessageSlot) -> Self {
        Self::SubmissionAccepted(SubmissionAcceptance::new(payload))
    }
    pub fn submission_rejected(payload: SubmissionRejectionReason) -> Self {
        Self::SubmissionRejected(SubmissionRejection::new(payload))
    }
    pub fn inbox_listing(payload: Messages) -> Self {
        Self::InboxListing(InboxListingReply::new(payload))
    }
    pub fn agent_identity_assigned(payload: AssignedAgentIdentity) -> Self {
        Self::AgentIdentityAssigned(payload)
    }
    pub fn agent_endpoint_bound(payload: AgentIdentifier) -> Self {
        Self::AgentEndpointBound(BoundAgentEndpoint::new(payload))
    }
    pub fn agent_registry_listing(payload: Entries) -> Self {
        Self::AgentRegistryListing(AgentRegistryListingReply::new(payload))
    }
    pub fn agent_registry_rejected(payload: AgentRegistryRejectionReason) -> Self {
        Self::AgentRegistryRejected(AgentRegistryRejection::new(payload))
    }
    pub fn message_request_unimplemented(
        payload: MessageRequestUnimplementedReply,
    ) -> Self {
        Self::MessageRequestUnimplemented(payload)
    }
    pub fn error(payload: ErrorMessage) -> Self {
        Self::Error(ErrorReport::new(payload))
    }
    pub fn thread_listing(payload: ThreadContents) -> Self {
        Self::ThreadListing(payload)
    }
    pub fn thread_subscribed(payload: ThreadSubscriptionAcknowledgment) -> Self {
        Self::ThreadSubscribed(payload)
    }
    pub fn thread_index_listing(payload: Threads) -> Self {
        Self::ThreadIndexListing(ThreadIndexEntries::new(payload))
    }
    pub fn thread_rejected(payload: ThreadRejectionReason) -> Self {
        Self::ThreadRejected(ThreadRejection::new(payload))
    }
}

#[rustfmt::skip]
impl From<ThreadName> for ThreadSelection {
    fn from(payload: ThreadName) -> Self {
        Self::Named(payload)
    }
}

#[rustfmt::skip]
impl From<UnixUserIdentifier> for ConnectionClass {
    fn from(payload: UnixUserIdentifier) -> Self {
        Self::NonOwnerUser(payload)
    }
}

#[rustfmt::skip]
impl From<SystemPrincipal> for ConnectionClass {
    fn from(payload: SystemPrincipal) -> Self {
        Self::System(payload)
    }
}

#[rustfmt::skip]
impl From<OtherPersonaEngine> for ConnectionClass {
    fn from(payload: OtherPersonaEngine) -> Self {
        Self::OtherPersona(payload)
    }
}

#[rustfmt::skip]
impl From<NetworkPeer> for ConnectionClass {
    fn from(payload: NetworkPeer) -> Self {
        Self::Network(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentName> for MessageOrigin {
    fn from(payload: ComponentName) -> Self {
        Self::Internal(payload)
    }
}

#[rustfmt::skip]
impl From<InternalComponentInstanceOrigin> for MessageOrigin {
    fn from(payload: InternalComponentInstanceOrigin) -> Self {
        Self::InternalComponentInstance(payload)
    }
}

#[rustfmt::skip]
impl From<ConnectionClass> for MessageOrigin {
    fn from(payload: ConnectionClass) -> Self {
        Self::External(payload)
    }
}

#[rustfmt::skip]
impl From<ResumeIdentity> for ResumeSelection {
    fn from(payload: ResumeIdentity) -> Self {
        Self::Resumed(payload)
    }
}

#[rustfmt::skip]
impl From<AgentEndpoint> for EndpointSelection {
    fn from(payload: AgentEndpoint) -> Self {
        Self::Bound(payload)
    }
}

#[rustfmt::skip]
impl From<HarnessProcessPin> for ProcessPinSelection {
    fn from(payload: HarnessProcessPin) -> Self {
        Self::Pinned(payload)
    }
}

#[rustfmt::skip]
impl From<AgentIdentifier> for AgentRegistryQuery {
    fn from(payload: AgentIdentifier) -> Self {
        Self::ByAgent(payload)
    }
}

#[rustfmt::skip]
impl From<ThreadRelation> for ThreadRelationSelection {
    fn from(payload: ThreadRelation) -> Self {
        Self::Related(payload)
    }
}

#[rustfmt::skip]
impl From<DependencyKind> for MessageUnimplementedReason {
    fn from(payload: DependencyKind) -> Self {
        Self::DependencyMissing(payload)
    }
}

#[rustfmt::skip]
impl From<ResourceKind> for MessageUnimplementedReason {
    fn from(payload: ResourceKind) -> Self {
        Self::ResourceUnavailable(payload)
    }
}

#[rustfmt::skip]
impl From<UnixUserIdentifier> for OwnerIdentity {
    fn from(payload: UnixUserIdentifier) -> Self {
        Self::UnixUser(payload)
    }
}

#[rustfmt::skip]
impl From<SystemPrincipal> for OwnerIdentity {
    fn from(payload: SystemPrincipal) -> Self {
        Self::System(payload)
    }
}

#[rustfmt::skip]
impl From<MessageSubmission> for Input {
    fn from(payload: MessageSubmission) -> Self {
        Self::Submit(payload)
    }
}

#[rustfmt::skip]
impl From<StampedMessageSubmission> for Input {
    fn from(payload: StampedMessageSubmission) -> Self {
        Self::SubmitStamped(payload)
    }
}

#[rustfmt::skip]
impl From<InboxQuery> for Input {
    fn from(payload: InboxQuery) -> Self {
        Self::QueryInbox(payload)
    }
}

#[rustfmt::skip]
impl From<AgentIdentityAssignment> for Input {
    fn from(payload: AgentIdentityAssignment) -> Self {
        Self::AssignAgentIdentity(payload)
    }
}

#[rustfmt::skip]
impl From<AgentEndpointBinding> for Input {
    fn from(payload: AgentEndpointBinding) -> Self {
        Self::BindAgentEndpoint(payload)
    }
}

#[rustfmt::skip]
impl From<AgentRegistryQuery> for Input {
    fn from(payload: AgentRegistryQuery) -> Self {
        Self::QueryAgentRegistry(payload)
    }
}

#[rustfmt::skip]
impl From<ThreadQuery> for Input {
    fn from(payload: ThreadQuery) -> Self {
        Self::QueryThread(payload)
    }
}

#[rustfmt::skip]
impl From<ThreadSubscription> for Input {
    fn from(payload: ThreadSubscription) -> Self {
        Self::SubscribeThread(payload)
    }
}

#[rustfmt::skip]
impl From<ThreadIndexQuery> for Input {
    fn from(payload: ThreadIndexQuery) -> Self {
        Self::QueryThreads(payload)
    }
}

#[rustfmt::skip]
impl From<SubmissionAcceptance> for Output {
    fn from(payload: SubmissionAcceptance) -> Self {
        Self::SubmissionAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<SubmissionRejection> for Output {
    fn from(payload: SubmissionRejection) -> Self {
        Self::SubmissionRejected(payload)
    }
}

#[rustfmt::skip]
impl From<InboxListingReply> for Output {
    fn from(payload: InboxListingReply) -> Self {
        Self::InboxListing(payload)
    }
}

#[rustfmt::skip]
impl From<AssignedAgentIdentity> for Output {
    fn from(payload: AssignedAgentIdentity) -> Self {
        Self::AgentIdentityAssigned(payload)
    }
}

#[rustfmt::skip]
impl From<BoundAgentEndpoint> for Output {
    fn from(payload: BoundAgentEndpoint) -> Self {
        Self::AgentEndpointBound(payload)
    }
}

#[rustfmt::skip]
impl From<AgentRegistryListingReply> for Output {
    fn from(payload: AgentRegistryListingReply) -> Self {
        Self::AgentRegistryListing(payload)
    }
}

#[rustfmt::skip]
impl From<AgentRegistryRejection> for Output {
    fn from(payload: AgentRegistryRejection) -> Self {
        Self::AgentRegistryRejected(payload)
    }
}

#[rustfmt::skip]
impl From<MessageRequestUnimplementedReply> for Output {
    fn from(payload: MessageRequestUnimplementedReply) -> Self {
        Self::MessageRequestUnimplemented(payload)
    }
}

#[rustfmt::skip]
impl From<ErrorReport> for Output {
    fn from(payload: ErrorReport) -> Self {
        Self::Error(payload)
    }
}

#[rustfmt::skip]
impl From<ThreadContents> for Output {
    fn from(payload: ThreadContents) -> Self {
        Self::ThreadListing(payload)
    }
}

#[rustfmt::skip]
impl From<ThreadSubscriptionAcknowledgment> for Output {
    fn from(payload: ThreadSubscriptionAcknowledgment) -> Self {
        Self::ThreadSubscribed(payload)
    }
}

#[rustfmt::skip]
impl From<ThreadIndexEntries> for Output {
    fn from(payload: ThreadIndexEntries) -> Self {
        Self::ThreadIndexListing(payload)
    }
}

#[rustfmt::skip]
impl From<ThreadRejection> for Output {
    fn from(payload: ThreadRejection) -> Self {
        Self::ThreadRejected(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::str::FromStr for Input {
    type Err = DotosDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        DotosSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as DotosEncode>::to_dotos(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::str::FromStr for Output {
    type Err = DotosDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        DotosSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as DotosEncode>::to_dotos(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_SUBMIT: u64 = 0x0000000100000001;
    pub const INPUT_SUBMIT_STAMPED: u64 = 0x0001000100000001;
    pub const INPUT_QUERY_INBOX: u64 = 0x0002000100000001;
    pub const INPUT_ASSIGN_AGENT_IDENTITY: u64 = 0x0003000100000001;
    pub const INPUT_BIND_AGENT_ENDPOINT: u64 = 0x0004000100000001;
    pub const INPUT_QUERY_AGENT_REGISTRY: u64 = 0x0005000100000001;
    pub const INPUT_QUERY_THREAD: u64 = 0x0006000100000001;
    pub const INPUT_SUBSCRIBE_THREAD: u64 = 0x0007000100000001;
    pub const INPUT_QUERY_THREADS: u64 = 0x0008000100000001;
    pub const OUTPUT_SUBMISSION_ACCEPTED: u64 = 0x0100000100000001;
    pub const OUTPUT_SUBMISSION_REJECTED: u64 = 0x0101000100000001;
    pub const OUTPUT_INBOX_LISTING: u64 = 0x0102000100000001;
    pub const OUTPUT_AGENT_IDENTITY_ASSIGNED: u64 = 0x0103000100000001;
    pub const OUTPUT_AGENT_ENDPOINT_BOUND: u64 = 0x0104000100000001;
    pub const OUTPUT_AGENT_REGISTRY_LISTING: u64 = 0x0105000100000001;
    pub const OUTPUT_AGENT_REGISTRY_REJECTED: u64 = 0x0106000100000001;
    pub const OUTPUT_MESSAGE_REQUEST_UNIMPLEMENTED: u64 = 0x0107000100000001;
    pub const OUTPUT_ERROR: u64 = 0x0108000100000001;
    pub const OUTPUT_THREAD_LISTING: u64 = 0x0109000100000001;
    pub const OUTPUT_THREAD_SUBSCRIBED: u64 = 0x010A000100000001;
    pub const OUTPUT_THREAD_INDEX_LISTING: u64 = 0x010B000100000001;
    pub const OUTPUT_THREAD_REJECTED: u64 = 0x010C000100000001;
    pub const HANDSHAKE_REQUEST: u64 = 0xFF00000100000001;
    pub const HANDSHAKE_REPLY: u64 = 0xFF01000100000001;
    pub const ENGINE_REFUSAL: u64 = 0xFF02000100000001;
}

#[rustfmt::skip]
pub enum ContractMarker {}
#[rustfmt::skip]
impl signal_frame::WireContract for ContractMarker {
    const BINDING: signal_frame::ContractBinding = signal_frame::ContractBinding::new(
        match signal_frame::ContractId::try_new(1u32) {
            Ok(contract) => contract,
            Err(_) => panic!("generated contract ID must be nonzero"),
        },
        match signal_frame::WireRevision::try_new(1u16) {
            Ok(revision) => revision,
            Err(_) => panic!("generated wire revision must be nonzero"),
        },
    );
}
#[rustfmt::skip]
/// Why the daemon refused to produce an ordinary reply.
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq
)]
pub enum EngineRefusalReason {
    /// The engine ran and rejected the request with its typed
    /// domain error; the rendered error text is the detail.
    Rejected,
    /// The engine layer could not serve the request at all.
    Unavailable,
}
#[rustfmt::skip]
impl std::fmt::Display for EngineRefusalReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Rejected => formatter.write_str("engine rejected the request"),
            Self::Unavailable => formatter.write_str("engine unavailable"),
        }
    }
}
#[rustfmt::skip]
/// The refusal reply a daemon writes when the engine failed, so
/// the caller receives a complete typed frame instead of a closed
/// socket it cannot distinguish from daemon death. The typed
/// engine error stays daemon-side; the wire carries the
/// classification plus the rendered error text.
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineRefusal {
    pub reason: EngineRefusalReason,
    pub detail: String,
}
#[rustfmt::skip]
impl EngineRefusal {
    pub fn rejected(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Rejected,
            detail,
        }
    }
    pub fn unavailable(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Unavailable,
            detail,
        }
    }
    pub fn encode_bound_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            signal_frame::SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&short_header::ENGINE_REFUSAL.to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    FrameEncode,
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    LegacyHeader { contract_id: u32, wire_revision: u16 },
    ContractMismatch { expected: u32, found: u32 },
    UnsupportedWireRevision { contract_id: u32, expected: u16, found: u16 },
    UnknownRoute { root: u8, variant: u8 },
    RouteBodyMismatch { root: u8, variant: u8, body: &'static str },
    UnexpectedFrameBody { found: &'static str },
    OperationCount { found: usize },
    EngineRefused { refusal: EngineRefusal },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::FrameEncode => {
                formatter.write_str("failed to encode bound signal frame")
            }
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::LegacyHeader { contract_id, wire_revision } => {
                write!(
                    formatter,
                    "legacy unbound signal frame ({contract_id}, {wire_revision})"
                )
            }
            Self::ContractMismatch { expected, found } => {
                write!(
                    formatter,
                    "signal contract mismatch: expected {expected}, found {found}"
                )
            }
            Self::UnsupportedWireRevision { contract_id, expected, found } => {
                write!(
                    formatter,
                    "unsupported wire revision for contract {contract_id}: expected {expected}, found {found}"
                )
            }
            Self::UnknownRoute { root, variant } => {
                write!(formatter, "unknown bound signal route ({root}, {variant})")
            }
            Self::RouteBodyMismatch { root, variant, body } => {
                write!(
                    formatter,
                    "bound signal route ({root}, {variant}) does not carry {body}"
                )
            }
            Self::UnexpectedFrameBody { found } => {
                write!(formatter, "expected one request frame, found {found}")
            }
            Self::OperationCount { found } => {
                write!(formatter, "expected one request operation, found {found}")
            }
            Self::EngineRefused { refusal } => {
                write!(formatter, "{}: {}", refusal.reason, refusal.detail)
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}
#[rustfmt::skip]
impl ContractMarker {
    pub fn handshake_request_frame(request: signal_frame::HandshakeRequest) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(0),
            ),
            FrameBody::HandshakeRequest(request),
        )
    }
    pub fn handshake_reply_frame(reply: signal_frame::HandshakeReply) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(1),
            ),
            FrameBody::HandshakeReply(reply),
        )
    }
    pub fn decode_frame(bytes: &[u8]) -> Result<Frame, SignalFrameError> {
        if bytes.len() < signal_frame::SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: bytes.len(),
            });
        }
        let mut header_bytes = [0_u8; signal_frame::SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&bytes[..signal_frame::SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let contract_id = header as u32;
        let wire_revision = (header >> 32) as u16;
        if contract_id == 0 || wire_revision == 0 {
            return Err(SignalFrameError::LegacyHeader {
                contract_id,
                wire_revision,
            });
        }
        if contract_id != 1u32 {
            return Err(SignalFrameError::ContractMismatch {
                expected: 1u32,
                found: contract_id,
            });
        }
        if wire_revision != 1u16 {
            return Err(SignalFrameError::UnsupportedWireRevision {
                contract_id,
                expected: 1u16,
                found: wire_revision,
            });
        }
        let root = (header >> 56) as u8;
        let variant = (header >> 48) as u8;
        match (root, variant) {
            (0, 0)
            | (0, 1)
            | (0, 2)
            | (0, 3)
            | (0, 4)
            | (0, 5)
            | (0, 6)
            | (0, 7)
            | (0, 8)
            | (1, 0)
            | (1, 1)
            | (1, 2)
            | (1, 3)
            | (1, 4)
            | (1, 5)
            | (1, 6)
            | (1, 7)
            | (1, 8)
            | (1, 9)
            | (1, 10)
            | (1, 11)
            | (1, 12)
            | (0xff, 0)
            | (0xff, 1)
            | (0xff, 2) => {}
            _ => {
                return Err(SignalFrameError::UnknownRoute {
                    root,
                    variant,
                });
            }
        }
        if (root, variant) == (0xff, 2) {
            let refusal = rkyv::from_bytes::<
                EngineRefusal,
                rkyv::rancor::Error,
            >(&bytes[signal_frame::SHORT_HEADER_BYTE_COUNT..])
                .map_err(|_| SignalFrameError::ArchiveDecode)?;
            return Err(SignalFrameError::EngineRefused {
                refusal,
            });
        }
        let frame = Frame::decode(bytes).map_err(|_| SignalFrameError::ArchiveDecode)?;
        let header_route = signal_frame::WireRoute::new(
            signal_frame::RootCode::new(root),
            signal_frame::VariantCode::new(variant),
        );
        let body_matches = match frame.body() {
            FrameBody::HandshakeRequest(_) => (root, variant) == (0xff, 0),
            FrameBody::HandshakeReply(_) => (root, variant) == (0xff, 1),
            FrameBody::Request { request, .. } => {
                request.route().is_ok_and(|route| route == header_route)
            }
            FrameBody::Reply { reply, .. } => {
                match reply {
                    signal_frame::Reply::Accepted { per_operation, .. } => {
                        match per_operation.head() {
                            signal_frame::SubReply::Ok(output) => {
                                output.wire_route() == header_route
                            }
                            signal_frame::SubReply::Failed {
                                detail: Some(output),
                                ..
                            } => output.wire_route() == header_route,
                            signal_frame::SubReply::Invalidated
                            | signal_frame::SubReply::Failed { detail: None, .. }
                            | signal_frame::SubReply::Skipped => root == 1,
                        }
                    }
                    signal_frame::Reply::Rejected { .. } => root == 1,
                }
            }
        };
        if !body_matches {
            let body = match frame.body() {
                FrameBody::HandshakeRequest(_) => "handshake request",
                FrameBody::HandshakeReply(_) => "handshake reply",
                FrameBody::Request { .. } => "request",
                FrameBody::Reply { .. } => "reply",
            };
            return Err(SignalFrameError::RouteBodyMismatch {
                root,
                variant,
                body,
            });
        }
        Ok(frame)
    }
    pub fn decode_single_request(
        bytes: &[u8],
    ) -> Result<(signal_frame::ExchangeIdentifier, Input), SignalFrameError> {
        let frame = Self::decode_frame(bytes)?;
        match frame.into_body() {
            FrameBody::Request { exchange, request } => {
                let found = request.payloads().len();
                if found != 1 {
                    return Err(SignalFrameError::OperationCount {
                        found,
                    });
                }
                Ok((exchange, request.payloads.into_head()))
            }
            FrameBody::HandshakeRequest(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake request",
                })
            }
            FrameBody::HandshakeReply(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake reply",
                })
            }
            FrameBody::Reply { .. } => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "reply",
                })
            }
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Submit,
    SubmitStamped,
    QueryInbox,
    AssignAgentIdentity,
    BindAgentEndpoint,
    QueryAgentRegistry,
    QueryThread,
    SubscribeThread,
    QueryThreads,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    SubmissionAccepted,
    SubmissionRejected,
    InboxListing,
    AgentIdentityAssigned,
    AgentEndpointBound,
    AgentRegistryListing,
    AgentRegistryRejected,
    MessageRequestUnimplemented,
    Error,
    ThreadListing,
    ThreadSubscribed,
    ThreadIndexListing,
    ThreadRejected,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Submit(_) => InputRoute::Submit,
            Self::SubmitStamped(_) => InputRoute::SubmitStamped,
            Self::QueryInbox(_) => InputRoute::QueryInbox,
            Self::AssignAgentIdentity(_) => InputRoute::AssignAgentIdentity,
            Self::BindAgentEndpoint(_) => InputRoute::BindAgentEndpoint,
            Self::QueryAgentRegistry(_) => InputRoute::QueryAgentRegistry,
            Self::QueryThread(_) => InputRoute::QueryThread,
            Self::SubscribeThread(_) => InputRoute::SubscribeThread,
            Self::QueryThreads(_) => InputRoute::QueryThreads,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::Submit(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::SubmitStamped(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(1),
                )
            }
            Self::QueryInbox(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(2),
                )
            }
            Self::AssignAgentIdentity(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(3),
                )
            }
            Self::BindAgentEndpoint(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(4),
                )
            }
            Self::QueryAgentRegistry(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(5),
                )
            }
            Self::QueryThread(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(6),
                )
            }
            Self::SubscribeThread(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(7),
                )
            }
            Self::QueryThreads(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(8),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Submit(_) => short_header::INPUT_SUBMIT,
            Self::SubmitStamped(_) => short_header::INPUT_SUBMIT_STAMPED,
            Self::QueryInbox(_) => short_header::INPUT_QUERY_INBOX,
            Self::AssignAgentIdentity(_) => short_header::INPUT_ASSIGN_AGENT_IDENTITY,
            Self::BindAgentEndpoint(_) => short_header::INPUT_BIND_AGENT_ENDPOINT,
            Self::QueryAgentRegistry(_) => short_header::INPUT_QUERY_AGENT_REGISTRY,
            Self::QueryThread(_) => short_header::INPUT_QUERY_THREAD,
            Self::SubscribeThread(_) => short_header::INPUT_SUBSCRIBE_THREAD,
            Self::QueryThreads(_) => short_header::INPUT_QUERY_THREADS,
        }
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::SubmissionAccepted(_) => OutputRoute::SubmissionAccepted,
            Self::SubmissionRejected(_) => OutputRoute::SubmissionRejected,
            Self::InboxListing(_) => OutputRoute::InboxListing,
            Self::AgentIdentityAssigned(_) => OutputRoute::AgentIdentityAssigned,
            Self::AgentEndpointBound(_) => OutputRoute::AgentEndpointBound,
            Self::AgentRegistryListing(_) => OutputRoute::AgentRegistryListing,
            Self::AgentRegistryRejected(_) => OutputRoute::AgentRegistryRejected,
            Self::MessageRequestUnimplemented(_) => {
                OutputRoute::MessageRequestUnimplemented
            }
            Self::Error(_) => OutputRoute::Error,
            Self::ThreadListing(_) => OutputRoute::ThreadListing,
            Self::ThreadSubscribed(_) => OutputRoute::ThreadSubscribed,
            Self::ThreadIndexListing(_) => OutputRoute::ThreadIndexListing,
            Self::ThreadRejected(_) => OutputRoute::ThreadRejected,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::SubmissionAccepted(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::SubmissionRejected(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(1),
                )
            }
            Self::InboxListing(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(2),
                )
            }
            Self::AgentIdentityAssigned(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(3),
                )
            }
            Self::AgentEndpointBound(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(4),
                )
            }
            Self::AgentRegistryListing(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(5),
                )
            }
            Self::AgentRegistryRejected(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(6),
                )
            }
            Self::MessageRequestUnimplemented(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(7),
                )
            }
            Self::Error(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(8),
                )
            }
            Self::ThreadListing(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(9),
                )
            }
            Self::ThreadSubscribed(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(10),
                )
            }
            Self::ThreadIndexListing(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(11),
                )
            }
            Self::ThreadRejected(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(12),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::SubmissionAccepted(_) => short_header::OUTPUT_SUBMISSION_ACCEPTED,
            Self::SubmissionRejected(_) => short_header::OUTPUT_SUBMISSION_REJECTED,
            Self::InboxListing(_) => short_header::OUTPUT_INBOX_LISTING,
            Self::AgentIdentityAssigned(_) => {
                short_header::OUTPUT_AGENT_IDENTITY_ASSIGNED
            }
            Self::AgentEndpointBound(_) => short_header::OUTPUT_AGENT_ENDPOINT_BOUND,
            Self::AgentRegistryListing(_) => short_header::OUTPUT_AGENT_REGISTRY_LISTING,
            Self::AgentRegistryRejected(_) => {
                short_header::OUTPUT_AGENT_REGISTRY_REJECTED
            }
            Self::MessageRequestUnimplemented(_) => {
                short_header::OUTPUT_MESSAGE_REQUEST_UNIMPLEMENTED
            }
            Self::Error(_) => short_header::OUTPUT_ERROR,
            Self::ThreadListing(_) => short_header::OUTPUT_THREAD_LISTING,
            Self::ThreadSubscribed(_) => short_header::OUTPUT_THREAD_SUBSCRIBED,
            Self::ThreadIndexListing(_) => short_header::OUTPUT_THREAD_INDEX_LISTING,
            Self::ThreadRejected(_) => short_header::OUTPUT_THREAD_REJECTED,
        }
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Submit",
        "SubmitStamped",
        "QueryInbox",
        "AssignAgentIdentity",
        "BindAgentEndpoint",
        "QueryAgentRegistry",
        "QueryThread",
        "SubscribeThread",
        "QueryThreads",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        let route = self.wire_route();
        u64::from(route.root().value()) | (u64::from(route.variant().value()) << 8)
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::BoundExchangeFrame<ContractMarker, Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let request = signal_frame::Request::from_payload(self);
        Frame::new(
            route,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
    pub fn encode_request_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_frame(exchange).encode().map_err(|_| SignalFrameError::FrameEncode)
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::new(
            route,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
    pub fn encode_reply_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_reply_frame(exchange)
            .encode()
            .map_err(|_| SignalFrameError::FrameEncode)
    }
}
